### ISSUE TITLE
Tensorflow probability error in `_fit_model_vi` 

### ISSUE THREAD

**Issue by ethanweinberger** [andrewcharlesjones/cplvm#2]
When attempting to fit a `CPLVM` model using the `_fit_model_vi` function, I ran into the following error:

<img width="930" alt="Screen Shot 2021-11-04 at 11 12 33 AM" src="https://user-images.githubusercontent.com/7200040/140396080-2ecffd66-280c-437b-8c71-00e56793cc22.png">

I suspect this may be due to some Tensorflow API update? When running this code I was on Tensorflow 2.5.0 (the oldest version available on pypi), though the package appears to have been developed using 2.3.0.

The code used to produce the above error is:

```
from cplvm import CPLVM

foreground_data = target_adata.layers['count'].T
background_data = background_adata.layers['count'].T

cplvm = CPLVM(k_shared=10, k_foreground=10)

approx_model = CPLVMLogNormalApprox(
    background_data,
    foreground_data,
    10,
    10
)

model_output = cplvm._fit_model_vi(
    background_data,
    foreground_data,
    approximate_model = approx_model,
    compute_size_factors=True,
    is_H0=False,
    offset_term=False
)
```

**Comment by andrewcharlesjones** [comment]
Hmm thanks for noticing this one too. I think this might be due to a mismatch between the specification CPLVM and the approximate model. For example, if the CPLVM has an `offset_term`, but the approximate model doesn't (or vice versa, which might be your case), you might see this error. 

I added a couple Exception raises that hopefully throw more informative messages, but let me know if you still run into issues.

**Comment by ethanweinberger** [comment]
Closing this since I'm no longer running into the issue. Thanks for the help!
